---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ $.Chart.Name }}
    spec:
      imagePullSecrets:
      - name: "registrysecret"
      containers:
      - name: assets
{{ tuple "assets" . | include "werf_container_image" | indent 8 }}
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx", "-s", "quit"]
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
      - name: basicapp
        command: ['gunicorn', 'django_example.wsgi:application', '--bind', '0.0.0.0:8001', '--access-logfile', '-', '--log-level', 'debug']
{{ tuple "basicapp" . | include "werf_container_image" | indent 8 }}
        workingDir: /app
        ports:
        - containerPort: 8001
          protocol: TCP
        env:
        - name: SECRET_KEY
          value: {{ pluck .Values.global.env .Values.app.secret_key | first | default .Values.app.secret_key._default }}
{{ tuple "basicapp" . | include "werf_container_env" | indent 8 }}
