---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ $.Chart.Name }}
    spec:
      imagePullSecrets:
      - name: "registrysecret"
      containers:
      - name: basicapp
        command: [__________]
{{ tuple "basicapp" . | include "werf_container_image" | indent 8 }}
        workingDir: /app
        ports:
        - containerPort: __________
          protocol: TCP
        env:
          __________
          __________
{{ tuple "basicapp" . | include "werf_container_env" | indent 8 }}
