---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: {{ .Chart.Name }}
spec:
  rules:
  - host: {{ .Values.global.ci_url }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Chart.Name }}
          servicePort: 80
      - backend:
          serviceName: {{ pluck .Values.global.env .Values.app.s3.host  | first | default .Values.app.s3.host._default }}
          servicePort: {{ pluck .Values.global.env .Values.app.s3.port  | first | default .Values.app.s3.port._default }}
        path: /{{ pluck .Values.global.env .Values.app.s3.bucket  | first | default .Values.app.s3.bucket._default }}/
