---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  env.json: |
    {
      "url": {{ pluck .Values.global.env .Values.app.url | first | default .Values.app.url._default |quote }}
    }
