---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Chart.Name }}
spec:
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: {{ $.Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ $.Chart.Name }}
    spec:
      imagePullSecrets:
      - name: "registrysecret"
      containers:
      - name: web-basic
{{ tuple "basicapp" . | include "werf_container_image" | indent 8 }}
        workingDir: /app
        command: ["node","/app/dist/app.js"]
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
{{ tuple "basicapp" . | include "werf_container_env" | indent 8 }}
      - name: assets
{{ tuple "assets" . | include "werf_container_image" | indent 8 }}
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx", "-s", "quit"]
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
        ports:
        - containerPort: 80
          name: http
          protocol: TCP