dependencies:
  - name: minio
    version: "3.3.6"
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
  - name: rabbitmq
    version: "6.25.5"
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: redis
    version: 9.3.2
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: redis.enabled
