dependencies:
  - name: minio
    version: "3.3.6"
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
  - name: rabbitmq
    version: "6.25.5"
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: redis
    version: "10.6.10"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
