app:
  isDebug:
    _default: "true"
    production: "false"
    testing: "true"
  redis:
    session_ttl:
      _default: "3600"
    cookie_secret:
      _default: "supersecret"
redis:
  fullnameOverride: redis
  nameOverride: redis
  _port:
    _default: 6379
  host:
    _default: redis-master
  master:
    persistence:
      enabled: false
  slave:
    persistence:
      enabled: false
  cluster:
    slaveCount: 1
