redis:
  master:
    persistence:
      enabled: false
  slave:
    persistence:
      enabled: false
  cluster:
    slaveCount: 1

postgresql:
  persistence:
    storageClass: "local-storage"
    accessModes:
    - ReadWriteOnce
    size: 8Gi
    annotations: {}

rabbitmq:
  rabbitmq:
    username: chat
  persistence:
    storageClass: "local-storage"
    accessMode: ReadWriteOnce
    size: 4Gi
  ingress:
    enabled: true
    hostName: rabbit.superprod.alfa-team.hf.flant.com
    path: /
    tls: false

minio:
  persistence:
    enabled: true
    storageClass: "local-storage"
    accessMode: ReadWriteOnce
    size: 2Gi

app:
  s3:
    host:
      _default: krovatka-test-minio
    port:
      _default: 9000
    bucket:
      _default: 'avatars'
    ssl:
      _default: 'false'
  cdn_prefix:
    _default: '/'
  postgresql:
    host:
      _default: krovatka-test-postgresql
    user: 
      _default: chat
    db: 
      _default: chat
    port:
      _default: 5432
  rabbitmq:
    host:
      _default: krovatka-test-rabbitmq
    vhost:
      _default: ""
    user:
      _default: chat
    port:
      _default: 5672
  redis:
    host:
      master:
        _default: krovatka-test-redis-master
      slave:
        _default: krovatka-test-redis-slave
