---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: {{ .Chart.Name }}
spec:
  rules:
  - host: krovatka.superprod.alfa-team.hf.flant.com
    http:
      paths:
      - backend:
          serviceName: {{ .Chart.Name }}
          servicePort: 5000
        path: /
      - backend:
          serviceName: {{ pluck .Values.global.env .Values.app.s3.host  | first | default .Values.app.s3.host._default }}
          servicePort: {{ pluck .Values.global.env .Values.app.s3.port  | first | default .Values.app.s3.port._default }}
        path: /{{ pluck .Values.global.env .Values.app.s3.bucket  | first | default .Values.app.s3.bucket._default }}/
      - backend:
          serviceName:  {{ printf "%s-assets" .Chart.Name }}
          servicePort: 80
        path: /assets/
  tls:
  - hosts:
    - krovatka.superprod.alfa-team.hf.flant.com
    secretName: ingress-tls
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Chart.Name }}
spec:
  acme:
    config:
    - domains:
      - krovatka.superprod.alfa-team.hf.flant.com
      http01:
        ingressClass: nginx
  dnsNames:
  - krovatka.superprod.alfa-team.hf.flant.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: ingress-tls
