---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-py
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-py
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-py
    spec:
      imagePullSecrets:
      - name: "registrysecret"
      containers:
      - name: python
        command: ["python","/app/app.py"]
{{ tuple "python" . | include "werf_container_image" | indent 8 }}
        workingDir: /app
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: "DEBUG"
          value: "{{ pluck .Values.global.env .Values.app.isDebug | first | default .Values.app.isDebug._default }}"
{{ tuple "python" . | include "werf_container_env" | indent 8 }}
