---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name | quote }}
{{ tuple "basicapp" . | include "werf_container_image" | indent 8 }}
        command:
        - java
        - -jar
        - /app/target/demo.jar $JAVA_OPT
        workingDir: /app
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: JAVA_OPT
          value: {{ pluck .Values.global.env .Values.app.java_opt | first | default .Values.app.java_opt._default }}
        - name: REDIS_HOST
          value: {{ pluck .Values.global.env .Values.redis.host | first | default .Values.redis.host_default | quote }}
        - name: REDIS_PORT
          value: {{ pluck .Values.global.env .Values.redis._port | first | default .Values.redis._port_default | quote }}
        - name: REDIS_LOGIN
          value: {{ pluck .Values.global.env .Values.redis._login | first | default .Values.redis._login._default | quote }}
        - name: REDIS_PASSWORD
          value: {{ .Values.redis.password | quote }}
        - name: SESSION_TTL
          value: {{ pluck .Values.global.env .Values.app.redis.session_ttl | first | default .Values.redis.session_ttl_default | quote }}
        - name: COOKIE_SECRET
          value: {{ pluck .Values.global.env .Values.app.redis.cookie_secret | first | default .Values.app.redis.cookie_secret_default | quote }}
{{ tuple "basicapp" . | include "werf_container_env" | indent 8 }}
