---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
      - name: "registrysecret"
      containers:
      - name: basicapp
        command: ["/bin/bash"]
        args: ["-c", "java -jar /app/target/demo-1.0.jar $JAVA_OPT"]
{{ tuple "basicapp" . | include "werf_container_image" | indent 8 }}
        workingDir: /app
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: JAVA_OPT
          value: {{ pluck .Values.global.env .Values.app.java_opt | first | default .Values.app.java_opt._default }}
        - name: DBPASS
          value: "just_a_placeholder"
{{ tuple "basicapp" . | include "werf_container_env" | indent 8 }}
